export default {
  products: [
    {
      _id: 1,
      name: "Shirt",
      categorie: "Shirt",
      brand: "Reebok",
      image: "/images/shirt.jpg",
      rating: 10,
      numReviews: 10,
      price: 20,
      countInStock: 0,
    },
    {
      _id: 2,
      name: "Tight Pants",
      categorie: "Pants",
      brand: "Nike",
      image: "/images/pants.jpg",
      rating: 5,
      numReviews: 5,
      price: 60,
      countInStock: 6,
    },
    {
      _id: 3,
      name: "Slim Pants",
      categorie: "Shirt",
      brand: "Nike",
      image: "/images/pants.jpg",
      rating: 5,
      numReviews: 5,
      price: 660,
      countInStock: 6,
    },
    {
      _id: 4,
      name: "Pants",
      categorie: "Pants",
      brand: "Nike",
      image: "/images/pants.jpg",
      rating: 5,
      numReviews: 5,
      price: 360,
      countInStock: 6,
    },
    {
      _id: 5,
      name: "Pants",
      categorie: "Pants",
      brand: "Nike",
      image: "/images/shirt.jpg",
      rating: 5,
      numReviews: 5,
      price: 310,
      countInStock: 6,
    },
    {
      _id: 6,
      name: "Pants",
      categorie: "Pants",
      brand: "Nike",
      image: "/images/shirt.jpg",
      rating: 5,
      numReviews: 5,
      price: 330,
      countInStock: 3,
    },
  ],
};
