export const USER_SING_IN_REQUEST = "USER_SING_IN_REQUEST";
export const USER_SING_IN_SUCCESS = "USER_SING_IN_SUCCESS";
export const USER_SING_IN_FAIL = "USER_SING_IN_FAIL";

export const USER_REGISTER_REQUEST = "USER_REGISTER_REQUEST";
export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS";
export const USER_REGISTER_FAIL = "USER_REGISTER_FAIL";
