import shirt from "./images/shirt.jpg";
import pants from "./images/pants.jpg";

export const data = [
  {
    id: 1,
    name: "Shirt",
    categorie: "Shirt",
    brand: "Reebok",
    image: shirt,
    rating: 10,
    numReviews: 10,
    price: 20,
  },
  {
    id: 2,
    name: "Tight Pants",
    categorie: "Pants",
    brand: "Nike",
    image: pants,
    rating: 5,
    numReviews: 5,
    price: 60,
  },
  {
    id: 3,
    name: "Slim Pants",
    categorie: "Shirt",
    brand: "Nike",
    image: shirt,
    rating: 5,
    numReviews: 5,
    price: 660,
  },
  {
    id: 4,
    name: "Pants",
    categorie: "Pants",
    brand: "Nike",
    image: pants,
    rating: 5,
    numReviews: 5,
    price: 360,
  },
  {
    id: 5,
    name: "Pants",
    categorie: "Pants",
    brand: "Nike",
    image: pants,
    rating: 5,
    numReviews: 5,
    price: 310,
  },
  {
    id: 6,
    name: "Pants",
    categorie: "Pants",
    brand: "Nike",
    image: pants,
    rating: 5,
    numReviews: 5,
    price: 330,
  },
];
